name: Deploy Bicep to Dev

on:
  push:
    branches:
      - feature/dev
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Deploy to Dev Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Deploy Bicep to Dev
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP_DEV }}
          template: infra/main.bicep
          parameters: '@infra/environments/main.dev.bicepparam'
          deploymentMode: Incremental
          scope: ResourceGroup
