name: Deploy Infrastructure to Prd

on:
  push:
    branches:
      - master
  #      paths:
  #        - 'infra/**'
  workflow_dispatch:  # Allows manual triggering

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prd:
    name: Deploy Infrastructure to Prd Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}        

      - name: Deploy Resources
        run: |
          az deployment group create \
            --name 'prd' \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_PRD }} \
            --template-file ./infra/main.bicep \
            --parameters ./infra/environments/main.prd.bicepparam
        id: deploy